scalar DateTime

type Post {
    id: ID!
    user: User!
    content: String!
    createdAt: DateTime!
}

type SavedPost {
    savedPost: Post!
    createdAt: DateTime!
}

type countedPostsResponse {
    count: Int
    rows: [Post]
}

type countedSavedPostsResponse {
    count: Int
    rows: [SavedPost]
}

type Query {
    getAllPosts: [Post]
    getPost(id: ID!): Post
    getPostsByUser(id: ID!): countedPostsResponse
    getAllSavedPosts(id: ID!): countedSavedPostsResponse
}

type Mutation {
    createPost(
        userId: ID!, 
        content: String!
    ): Post
    deletePost(id: ID!): String!
    updatePost(
        id: ID!,
        content: String!
    ): Post
    savePost(
        userId: ID!,
        postId: ID!
    ): String
    unsavePost(
        userId: ID!,
        postId: ID!
    ): String
}