scalar DateTime

type User {
    id: ID!
    username: String!
    email: String!
    name: String
    description: String
    avatarUrl: String
    bannerUrl: String
    createdAt: DateTime!
}

type row {
    createdAt: String
    follower: User!
    following: User!
}

type countedFollowsResponse {
    count: Int
    rows: [row]
}

type Query {
    getAllUsers: [User!]!
    getUser(id: ID!): User
    getAllFollowers(userId: ID!): countedFollowsResponse 
    getAllFollowings(userId: ID!): countedFollowsResponse
}

type Mutation {
    createUser(
        username: String!,
        email: String!, 
        passwordHash: String!, 
        name: String
    ): User 
    deleteUser(id: ID!): String!
    updateUser(
        id: ID!, 
        username: String, 
        email: String, 
        passwordHash: String, 
        name: String, 
        description: String, 
        avatarUrl: String, 
        bannerUrl: String
    ): User
    addFollow(
        followerId: ID!,
        followingId: ID!
    ): String!
    deleteFollow(
        followerId: ID!,
        followingId: ID!
    ): String!
}